<?php
return array(
	'Tx_Builder_CodeGeneration_Extension_ExtensionGenerator' => 'FluidTYPO3\Builder\CodeGeneration\Extension\ExtensionGenerator',
	'Tx_Builder_CodeGeneration_Testing_ViewHelperTestCaseGenerator' => 'FluidTYPO3\Builder\CodeGeneration\Testing\ViewHelperTestCaseGenerator',
	'Tx_Builder_CodeGeneration_AbstractClassGenerator' => 'FluidTYPO3\Builder\CodeGeneration\AbstractClassGenerator',
	'Tx_Builder_CodeGeneration_AbstractCodeGenerator' => 'FluidTYPO3\Builder\CodeGeneration\AbstractCodeGenerator',
	'Tx_Builder_CodeGeneration_ClassGeneratorInterface' => 'FluidTYPO3\Builder\CodeGeneration\ClassGeneratorInterface',
	'Tx_Builder_CodeGeneration_CodeGeneratorInterface' => 'FluidTYPO3\Builder\CodeGeneration\CodeGeneratorInterface',
	'Tx_Builder_CodeGeneration_CodeTemplate' => 'FluidTYPO3\Builder\CodeGeneration\CodeTemplate',
	'Tx_Builder_Command_BuilderCommandController' => 'FluidTYPO3\Builder\Command\BuilderCommandController',
	'Tx_Builder_Controller_BackendController' => 'FluidTYPO3\Builder\Controller\BackendController',
	'Tx_Builder_Controller_FrontendController' => 'FluidTYPO3\Builder\Controller\FrontendController',
	'Tx_Builder_Result_FluidParserResult' => 'FluidTYPO3\Builder\Result\FluidParserResult',
	'Tx_Builder_Result_ParserResult' => 'FluidTYPO3\Builder\Result\ParserResult',
	'Tx_Builder_Result_ParserResultInterface' => 'FluidTYPO3\Builder\Result\ParserResultInterface',
	'Tx_Builder_Service_ClassAnalysisService' => 'FluidTYPO3\Builder\Service\ClassAnalysisService',
	'Tx_Builder_Service_ExtensionService' => 'FluidTYPO3\Builder\Service\ExtensionService',
	'Tx_Builder_Service_SyntaxService' => 'FluidTYPO3\Builder\Service\SyntaxService',
	'Tx_Builder_Utility_ExtensionUtility' => 'FluidTYPO3\Builder\Utility\ExtensionUtility',
	'Tx_Builder_Utility_GlobUtility' => 'FluidTYPO3\Builder\Utility\GlobUtility',
);
